version: '3'

services:
  maven:
    build: ./server
    expose:
      - 8181
    ports:
      - 8181:8088
    restart: always
    working_dir: /server
    volumes:
      - ./server/target:/mnt
    networks:
      - client
      
  react:
    build: ./client
    restart: always
    expose:
      - 80
    ports:
      - 80:80
    networks:
      - client
    links:
      - maven
    depends_on:
      - maven
  
networks:
  client: