
CREATE TYPE TYPE_QUERY AS ENUM ('ITEM','TITLE','DATE_EXPIRED','COMPANY','REQUIRE_YEAR','DATE_POST','DESCRIPTION','LINK','TAG','ADDRESS');

CREATE TABLE query_checker (
  ID SERIAL,
  WEB_ANALYTIC_ID int DEFAULT NULL,
  QUERY_TYPE TYPE_QUERY DEFAULT NULL,
  QUARY_VALUE varchar(250) DEFAULT NULL,
  IS_ACTIVE int DEFAULT NULL,
  CREATED timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID)
);


CREATE TABLE tag (
  ID SERIAL,
  NAME varchar(50) DEFAULT NULL,
  CREATED timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID)
);

CREATE TABLE web_analytic (
  ID SERIAL,
  NAME varchar(250) DEFAULT NULL,
  LINK varchar(250) DEFAULT NULL,
  IS_ACTIVE int DEFAULT NULL,
  CREATED timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID)
)